build-line failed handler

diff --git a/jenkins_jobs/build-line/Jenkinsfile b/jenkins_jobs/build-line/Jenkinsfile
--- a/jenkins_jobs/build-line/Jenkinsfile
+++ b/jenkins_jobs/build-line/Jenkinsfile
@@ -223,9 +223,16 @@ EOF
             set +e
             cd $script_path
 
-            # compile status: 6(build failed)
-            echo "./notify_status.py $devops_compile_id 6"
-            python3 notify_status.py $devops_compile_id 6
+            # check compile status is 2(init) or 5(compiling)
+            python3 notify_status.py $devops_compile_id 2 check
+            is_init=$?
+            python3 notify_status.py $devops_compile_id 5 check
+            is_compiling=$?
+            if [[ "$is_init" == "3" || "$is_compiling" == "3" ]]; then
+                # compile status: 6(build failed)
+                echo "./notify_status.py $devops_compile_id 6"
+                python3 notify_status.py $devops_compile_id 6
+            fi
 
             # devops_server server status 0(idle)
             echo "./update_db.py -t devops_server -k server_status -v 0 -w id -e $devops_host_id"
